# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shantanu Bhadoria
email: shantanu@cpan.org
description: > # this means to ignore newlines until "baseurl:"
  Hi, my name is Shantanu Bhadoria. I am a golang Gopher, Python Ninja and Perl Monk.
  Welcome to my home page. I currently live in Singapore . I am a regular contributor
  and a author of many open source packages at PyPI and CPAN. My work can be accessed
  at GoDoc, NPM, MetaCPAN, PyPi, Atmosphere or at GitHub. Get in touch with me at
  (+91)-7406111818
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.shantanubhadoria.com" # the base hostname & protocol for your site
twitter_username: shaggedelic
github_username:  shantanubhadoria

theme: jekyll-theme-hacker

# # Defaults
# defaults:
#   - scope:
#     path: assets/img
#   - values:
#     img: true

# Build settings
markdown: kramdown
